app/authentication/routes.py
from forms import UserLoginForm
from models import User, supabase
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import check_password_hash

auth = Blueprint('auth', __name__)

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        wallet_address = form.wallet_address.data

        if User.email_exists(email):
            flash('Email address already in use. Please use a different email.', 'error')
            return redirect(url_for('site.home'))

        user = User.create(email, password, wallet_address=wallet_address)
        if user:
            login_user(user)
            flash('You have successfully created a user account', 'User-created')
            return redirect(url_for('site.home'))
        else:
            flash('User creation failed', 'error')

    return render_template('site.home', form=form)

@auth.route('/signin', methods=['GET', 'POST'])
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        response = supabase.table('users').select('*').eq('email', email).execute()
        if len(response.data) > 0:
            user_data = response.data[0]
            if check_password_hash(user_data['password'], password):
                user = User(user_data['id'], user_data['email'])
                login_user(user)

                flash('Signed in successfully', 'success')
                return redirect(url_for('site.home'))

        flash('Invalid email or password', 'auth-failed')

    return render_template('site.home', form=form)

@auth.route('/delete_account', methods=['POST'])
@login_required
def delete_account():
    user_id = current_user.id
    if User.delete(user_id):
        logout_user()
        flash('Your account has been successfully deleted.', 'success')
    else:
        flash('Failed to delete your account. Please try again.', 'error')
    return redirect(url_for('site.home'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
import random
from forms import UserLoginForm
from flask_login import login_required, current_user
from models import User
from forms import UserLoginForm, UserUpdateForm
from flask import get_flashed_messages




site = Blueprint('site', __name__, static_folder='static', template_folder='site_templates')

@site.route('/')
def home():
    form = UserLoginForm()

    image_filenames = [
        '1.JPEG', '2.PNG', '3.PNG', '4.JPEG', '5.PNG', '6.PNG', '7.PNG', '8.PNG', '9.PNG', '10.PNG',
        '11.PNG', '12.JPEG', '13.JPEG', '14.JPEG', '15.JPEG', '16.JPEG', '17.JPEG', '18.JPEG', '19.JPEG', '20.JPEG',
        '21.JPEG', '22.JPEG', '23.JPEG', '24.JPEG', '25.JPEG', '26.JPEG', '27.JPEG', '28.JPEG', '29.JPEG', '30.JPEG',
        '31.JPEG', '32.JPEG', '33.jpeg', '34.JPEG', '35.JPEG', '36.JPEG', '37.JPEG', '38.JPEG', '39.JPEG', '40.JPEG',
        '41.JPEG', '42.JPEG', '43.JPEG', '44.PNG', '45.jpg', '46.jpg', '47.jpg', '48.jpg', '49.jpg', '50.jpg',
        '51.jpg', '52.jpg', '53.jpg', '54.jpg', '55.jpg', '56.jpg', '57.jpg', '58.JPEG', '59.JPEG', '60.JPEG',
        '61.JPEG', '62.JPEG', '63.JPEG', '64.JPEG', '65.JPEG', '66.JPEG', '67.JPEG', '68.GIF', '69.jpg', '70.jpg'
    ]
    
    random.shuffle(image_filenames)
    
    images = image_filenames[:70]

    flash_messages = []
    categories = ['error', 'User-created', 'success']
    for category in categories:
        messages = get_flashed_messages(category_filter=[category])
        if messages:
            flash_messages.extend(messages)

    

    return render_template('index.html', images=images, form=form, flash_messages=flash_messages)

@site.route('/redesign')
def redesign():
    form = UserLoginForm()
    
    return render_template('redesign.html', form=form)

@site.route('/nat')
def nat():
    form = UserLoginForm()

    return render_template('nat.html', form=form)

@site.route('/learn')
def learn():
    form = UserLoginForm()

    return render_template('learn.html', form=form)

@site.route('/expansion')
def expand():
    form = UserLoginForm()

    return render_template('expansion.html', form=form)

@site.route('/update_profile', methods=['GET', 'POST'])
@login_required
def update_profile():
    form = UserUpdateForm(obj=current_user, is_update=True)
   
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data if form.password.data else None
        wallet_address = form.wallet_address.data

        updated_user = User.update(current_user.id, email, password, wallet_address)
        
        if updated_user:
            flash('Your profile has been updated successfully!', 'success')
            return redirect(url_for('site.home'))
        else:
            flash('Failed to update your profile. Please try again.', 'error')

    return render_template('update_profile.html', form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://kit.fontawesome.com/e2c889255e.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
  <script src="{{ url_for('static', filename='base.js') }}" defer type="module"></script>
  <script src="{{ url_for('static', filename='forms.js') }}" defer></script>
  <title>Blockchain Technology</title>
  <style>
    nav {
        z-index: 10000;
    }
  </style>

</head>
<body class="bg-black">
  <nav class="bg-gradient-to-r from-[#FDFF9B] via-[#50FBD9] to-[#106857] shadow-2xl fixed w-full top-0 z-[10000]">
    <div class="navbar-content mx-auto max-w-7xl px-2 sm:px-6 lg:px-8 flex h-16 items-center justify-between">
        <div class="flex-shrink-0 flex items-center">
            <a href="{{ url_for('site.home') }}" class="flex items-center">
              <img 
                id="logo" 
                class="rounded-md" 
                src="{{ url_for('static', filename='images/logo.png') }}" 
                alt="Company Logo" 
                style="filter: hue-rotate(174deg) brightness(170%) saturate(200%);"
            >
              <span class="text-black ml-3 font-bold">Blockchain Technology</span>
            </a>
        </div>
        <div class="flex space-x-8">
            <a href="{{ url_for('site.home') }}" class="px-4 py-2 rounded-lg" id="link" data-text="Dashboard">Dashboard</a>
            <a href="{{ url_for('site.redesign') }}" class="px-4 py-2 rounded-lg" id="link" data-text="Redesign">Redesign</a>
            <a href="{{ url_for('site.nat') }}" class="px-4 py-2 rounded-lg" id="link" data-text="NAT">NAT</a>
            <a href="{{ url_for('site.learn')}}" class="px-4 py-2 rounded lg" id="link" data-text="Web3">Web3</a>
            <a href="{{ url_for('site.expand')}}" class="px-4 py-2 rounded lg" id="link" data-text="Expansion">Expansion</a>
        </div>


        <div class="popup-container" id="popup-container">
            {% with form=form %}
                {% include 'forms.html' %}
            {% endwith %}
        </div>

        
        <div class="relative ml-3 z-[10000]" id="loginSignupButtons">
            <button type="button" class="relative flex rounded-full bg-gray-800 text-black text-sm focus:outline-none focus:ring-2 focus:ring-slate-300 focus:ring-offset-2 focus:ring-offset-gray-800 hover:text-slate-300" id="user-menu-button" aria-expanded="false" aria-haspopup="true" data-text="">
                <span class="absolute -inset-1.5"></span>
                <span class="sr-only">Open user menu</span>
                <i class="fa-solid fa-user"></i>
            </button>

            <div class="user-menu hidden absolute right-0 z-[10000] mt-2 w-96 origin-top-right rounded-lg bg-gradient-to-r from-[#FDFF9B] via-[#50FBD9] to-[#106857] py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" style= "width: 10rem;">
                <button class="close-menu cursor-pointer w-[24px] h-[24px]">
                    <i class="fa-regular fa-circle-xmark"></i>
                </button>
                <ul>
                    {% if current_user.is_authenticated %}
                    <li>
                        <a href="{{ url_for('auth.logout') }}" class="block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="user-menu-item">Logout</a>
                    </li>
                    <li>
                        <a href="{{ url_for('site.update_profile') }}" class="block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="user-menu-item">Update Profile</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="#" class="LO block px-4 py-2 text-sm show-login" role="menuitem" tabindex="-1" id="show-login">Sign In</a>
                    </li>
                    <li>
                        <a href="#" class="SU block px-4 py-2 text-sm show-signup" role="menuitem" tabindex="-1" id="show-signup">Create Account</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
</body>
</html>

app/templates/forms.html
<script src="{{ url_for('static', filename='forms.js') }}"></script>
<script src="https://kit.fontawesome.com/e2c889255e.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">

<button class="swap">
    <button class="L" type="button" id="link" data-text="Sign In">Sign In</button>
    <button class="S" type="button" id="link" data-text="SignUp">SignUp</button>
</button>

<div class="popup-overlay">
    <div class="popup">
        <button class="close-btn">&times;</button>
        <!-- Login Form -->
        <div class="login-form">
            <h2 id="login-heading" class="text-xl font-bold text-center mb-4">Login to everlasting technology <i class="fa-brands fa-btc"></i></h2>
            <form id="signin-form" method="POST" action="{{ url_for('auth.signin') }}">
                {{ form.hidden_tag() }}

                <div class="form-element mb-4">
                    <fieldset id="login-email-field" class="text-sm">
                        {{ form.email.label }}
                        {{ form.email(class='form-control w-full p-2 rounded-md', placeholder='Enter your email address') }}
                    </fieldset>
                    <span class="underline block h-1 bg-black"></span>
                </div>
                <div class="form-element mb-4">
                    <fieldset id="login-pass-field" class="text-sm">
                        {{ form.password.label }}
                        {{ form.password(class='form-control w-full p-2 rounded-md', placeholder='Enter your password') }}
                        <span class="underline block h-1 bg-black"></span>
                    </fieldset>
                </div>
                <div class="form-element mb-4 flex items-center">
                    <input type="checkbox" id="remember-me" class="mr-2">
                    <label for="remember-me">Remember me</label>
                </div>
                <div class="form-element">
                    <button class="submit" type="submit" id="link" data-text="Sign In">Sign In</button>
                </div>
                <div class="form-element text-center">
                    <a href="#" class="FP">Forgot password?</a>
                </div>
            </form>
        </div>

        <!-- Signup Form -->
        <div class="signup-form form-wrapper" style="display: none;">
            <h2 id="signup-heading" class="text-xl font-bold text-center mb-4">IT'S FREE99! Learn about the everlasting blockchain <i class="fa-brands fa-btc"></i></h2>
            <form id="signup-form" method="POST" action="{{ url_for('auth.signup') }}">
                {{ form.hidden_tag() }}

                <div class="form-element mb-4">
                    <fieldset id="signup-email-field" class="text-sm">
                        {{ form.email.label }} (Required)
                        {{ form.email(class='form-control w-full p-2 rounded-md', placeholder='Enter your email address') }}
                    </fieldset>
                    <span class="underline block h-1 bg-black"></span>
                </div>
                <div class="form-element mb-4">
                    <fieldset id="sign-up-pass-field" class="text-sm">
                        {{ form.password.label }}
                        {{ form.password(class='form-control w-full p-2 rounded-md', placeholder='Enter your password') }}
                        <span class="underline block h-1 bg-black"></span>
                    </fieldset>
                </div>
                <div class="form-element mb-4">
                    <fieldset id="signup-wallet-address-field" class="text-sm">
                      {{ form.wallet_address.label }}
                      {{ form.wallet_address(class='form-control w-full p-2 rounded-md', placeholder='Enter your wallet address') }}
                      <span class="underline block h-1 bg-black"></span>
                    </fieldset>
                  </div>
                <div class="form-element">
                    <button class="submit" type="submit" id="link" data-text="SignUp">Sign Up</button>
                </div>
            </form>
        </div>
    </div>
</div>